### ISSUE TITLE
Compilation and installation problems

### ISSUE THREAD

**Issue by zhangjian420** [fbacchella/jrds#80]
Is it possible to provide an installation document to guide the compilation and installation?

JDK1.8
An error is reported when running `mvn clean install -DskipTests` 
![Snipaste_2022-06-14_13-23-34](https://user-images.githubusercontent.com/293321/173499705-bc08838d-867b-4e99-8469-b8c7b112d572.png)

**Comment by fbacchella** [comment]
Should be fixed now.

**Comment by zhangjian420** [comment]
> Should be fixed now.

Didn't fix it, still the same error
![Snipaste_2022-06-15_18-12-04](https://user-images.githubusercontent.com/293321/173803290-230d49c5-df71-4cc1-8096-af50cbab8e9b.png)

**Comment by zhangjian420** [comment]
> Should be fixed now.

After I switched to jdk17, I got a jrds-webapp-2022.1-SNAPSHOT.war file under jrds\jrds-webapp\target through mvn clean install -DskipTests, this file cannot be run under Tomcat10, the error is as follows:

![Snipaste_2022-06-16_10-48-15](https://user-images.githubusercontent.com/293321/173980458-2769704d-7203-4462-b14d-587c148dfc8f.png)

**Comment by fbacchella** [comment]
You build jrds with an (old) jre, not a jdk.
If you look at the stack, there is not a single method called from jrds. So I think you have a problem with your tomcat installation.

**Comment by zhangjian420** [comment]
> You build jrds with an (old) jre, not a jdk. If you look at the stack, there is not a single method called from jrds. So I think you have a problem with your tomcat installation.

Still unsuccessful.

I still recommend that you provide an installation tutorial for us to learn and use better
